### ISSUE TITLE
Change LeftMenu Width in Android Marshmallow

### ISSUE THREAD

**Issue by ghost** [SpecialCyCi/AndroidResideMenu#103]
Is there a way to change the leftmenu width in android Marshmallow.
I used this code and it working in Lollipop and under, but it seems that it's ignored in android M

```
    public void setWidth() {
        try {
            // getting type of the field from superClass
            Field privateLeftScrollMenu = ResideMenu.class.getDeclaredField("scrollViewLeftMenu");
            // transform this field to public
            privateLeftScrollMenu.setAccessible(true);
            // getting value from this field which is reference to a TextView
            ScrollView sv = (ScrollView) privateLeftScrollMenu.get(this);
            //finaly setting the Typface
            sv.setLayoutParams(new ViewGroup.LayoutParams(350, ViewGroup.LayoutParams.MATCH_PARENT));
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }

    }
```

This how is looking in android M
![screenshot_20160715-134410](https://cloud.githubusercontent.com/assets/10530308/16874607/3c790f30-4a92-11e6-962d-d57cf0d86de0.png)

**Comment by onuryurtturk** [comment]
same problem :/ any solution?

**Comment by ghost** [comment]
@onuryurtturk I had to import the projet as a library and modify the width of the menu manually

**Comment by joShinichi** [comment]
how to add library residemenu as a module? thanks

**Comment by ghost** [comment]
@joShinichi 
You can follow this tutorial
[Library-Project/Module as Dependency in Android Studio](http://www.theappguruz.com/blog/library-project-module-as-dependency-in-android-studio)

**Comment by onuryurtturk** [comment]
@smidaharoun thanks :thumbsup:
