### ISSUE TITLE
cannot set height of open menu

### ISSUE THREAD

**Issue by afiqiqmal** [SpecialCyCi/AndroidResideMenu#122]
Hi, How to set height of residemenu when opening the menu.. if i set 0.4, its height too small instead of 80% height. What i want to set the height is like below image..

![screen shot 2017-01-24 at 11 52 05 am](https://cloud.githubusercontent.com/assets/9051312/22233520/ad864f7c-e22b-11e6-85d3-00a2f1d5779e.png)

**Comment by niteshsirohi1** [comment]
how you have done this?
