### ISSUE TITLE
Execution failed in android studio 3.0

### ISSUE THREAD

**Issue by billu9t3** [SpecialCyCi/AndroidResideMenu#136]
Unable to run my app when it is added in gradle after updated android studio to 3.0.

this is error message kindly resolve it.

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by billu9t3** [comment]
Actually the issue is that i have added two libraries in my app and they both at the same time dont work i dont know why, why they conflict so i removed one and it solved the issue for me.

**Comment by gsDreamTech** [comment]
which are those libraries
