### ISSUE TITLE
How to add dividers below each menu item ?

### ISSUE THREAD

**Issue by jas017** [SpecialCyCi/AndroidResideMenu#23]
![zne4t](https://cloud.githubusercontent.com/assets/6624875/4303117/1d9d4e84-3e62-11e4-974f-53b546dd95ef.png)

**Comment by dadu1** [comment]
How can I show divider of length such that my divider of menu items will not overlap on reside menu?I want dynamic solution I don't want to keep fix layout width like 250 dp in reside menu item layout?
