### ISSUE TITLE
excellent work!I dump the view tree,found some layouts between decorView and contentView  which are redundant.

### ISSUE THREAD

**Issue by whysqwhw** [SpecialCyCi/AndroidResideMenu#37]
private void initValue(Activity activity) {
		this.activity = activity;
		leftMenuItems = new ArrayList<ResideMenuItem>();
		rightMenuItems = new ArrayList<ResideMenuItem>();
		ignoredViews = new ArrayList<View>();

		viewDecor = (ViewGroup) activity.getWindow().getDecorView();
		viewActivity = new TouchDisableView(this.activity);
		// View mContent = viewDecor.getChildAt(0);
		// viewDecor.removeViewAt(0);
		ViewGroup contentView = (ViewGroup) (viewDecor.findViewById(android.R.id.content));
		View mContent = contentView.getChildAt(0);
		contentView.removeAllViews();
		viewDecor.removeAllViews();

		viewActivity.setContent(mContent);
		addView(viewActivity);

		ViewGroup parent = (ViewGroup) scrollViewLeftMenu.getParent();
		parent.removeView(scrollViewLeftMenu);
		parent.removeView(scrollViewRightMenu);
	}

**Comment by SpecialCyCi** [comment]
Fixed.
