### ISSUE TITLE
How set onclick listener

### ISSUE THREAD

**Issue by Ofiro** [SpecialCyCi/AndroidResideMenu#41]
i used this 
ResideMenuItem rightItems = new ResideMenuItem(this, icon[i], options[i]);
            rightItems.setOnClickListener(this);

but how i can listen to the specific item on the onClick method?

**Comment by khan-tm** [comment]
Where's **onItemClickListener**?

**Comment by hamzaahmedkhan** [comment]
change this with new OnClickListener, like this.
ResideMenuItem rightItems = new ResideMenuItem(this, icon[i], options[i]);
rightItems.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        // Do task here
                    }
                });

**Comment by khan-tm** [comment]
I didn't mean that. I wanted to have a combine listener for all items. Well thanks @hamzaahmedkhan. :+1:
