### ISSUE TITLE
Error when import latest version

### ISSUE THREAD

**Issue by tomkui32** [SpecialCyCi/AndroidResideMenu#74]
hello, 

I got some problem during I import the project.
After I download and import the latest version of project, I got some error in ResideMenu.java.
For example, Error : "The method hideScrollViewMenu(ScrollView) in the type ResideMenu is not applicable for the arguments (View)" at line 438 hideScrollViewMenu(scrollViewLeftMenu); 
I am using eclispe. 
Thank you!

**Comment by SpecialCyCi** [comment]
Hey, tomkui, thanks for report.
I had fix it and push to master branch.

https://github.com/SpecialCyCi/AndroidResideMenu/commit/b77c3c41d74b786a6fcb56dcb5380e72d5e1d843
