### ISSUE TITLE
 3D support works bad

### ISSUE THREAD

**Issue by jushlwest** [SpecialCyCi/AndroidResideMenu#79]
Screen jumps and twitches irregularly, sometimes the menu disappears forever or displaced.
Android 6.0

**Comment by SpecialCyCi** [comment]
https://github.com/SpecialCyCi/AndroidResideMenu/pull/67
@LivioGama Hey, man. It seem like that 3D support works bad in Android 6.0?

**Comment by jushlwest** [comment]
Yes, but I can't test it on other versions. I will provide screenshot later.

**Comment by LivioGama** [comment]
I tried on Genymotion Preview Google Nexus 5X 6.0 and it works like a charm. Can you please provide more details (device used, have you tried on a blank project, etc..) on the use case @jushlwest ?

**Comment by LivioGama** [comment]
Ok got it, I didn't support 3D when dragging, the bug exist on under 6.0 too. Making you a pull request ;)

**Comment by jushlwest** [comment]
Ok

**Comment by SpecialCyCi** [comment]
:+1: Thanks @LivioGama
